### ISSUE TITLE
Players do not die when time runs out with Project MMO

### ISSUE THREAD

**Issue by deadlymango** [blay09/HardcoreRevival#54]
Hello, 

I have found that this mod does not behave properly when Project MMO is installed. When the player would die, and Hardcore Revival's KO screen shows up, when it comes time for the player to actually die, they do not. Instead, they are revived on the spot with half a heart remaining. The only way I have found for the player to truly die is to issue the /kill command on the player. 

Minecraft version is 1.16.5.
Forge version is 36.1.23.
The only mods that were in use are Project MMO 3.57.2 and Hardcore Revival 6.0.0
These two mods were tested in a freshly created Forge directory. No configuration files were touched.

Here is a link to a video of the issue that I am experiencing. I couldn't attach it to this message since the video was bigger than 10 MB. https://files.catbox.moe/sist6z.mp4

**Comment by PliskintheSaltyFork** [comment]
I haven't had this problem, but this might or might not be related, but when I respawn it sometimes instanta kills me at my respawn location.  This could be a problem with Scaling Health, but I'm not sure since I've set my starting health to 1 heart because I am trying to do a 1 heart monk mod challenge.

Minecraft: 1.12.2
Forge: 14.23.5.2855
Hardcore Revival: 1.2.0
Project MMO: 3.44.3
Scaling Health: 1.3.42+147

**Comment by BlayTheNinth** [comment]
This seems to have resolved itself in 1.20, can no longer reproduce
